<?php

/** @var \Magento\Framework\View\Element\AbstractBlock $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Macademy\Blog\ViewModel\Post $postVm */

$postVm = $block->getData('post_vm');

?>

<div class="blog-post-list">
<h1><?= __('Blog Posts') ?></h1>
<ul>
<?php foreach ($postVm->getList() as $post): ?>
<li><p><a href="<?= $block->getUrl('blog/post/detail/', ['id' => $post->getData('id')]) ?>"><?= __($post->getData($escaper->escapeHtml('title'))) ?></a></p></li>
<?php endforeach ?>
</ul>
<p><em><?= __('Total Count: %1', $postVm->count()) ?></em></p>
</div>
