<?php

/** @var \Magento\Framework\View\Element\AbstractBlock $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Macademy\Blog\ViewModel\Post $postVm */

$postVm = $block->getData('post_vm');

?>
<div class="blog-post-sidebar">
<p><?= __('Blog Post Sidebar') ?></p>
<ul>
<?php foreach ($postVm->getList() as $post): ?>
<li><p><a href="<?= $block->getUrl('blog/post/detail/', ['id' => $post->getData('id')]) ?>"><?= $escaper->escapeHtml(__($post->getData('title'))) ?></a></p></li>
<?php endforeach ?>
</ul>
</div>
