<?php
/**
@var \Macademy\CustomCheckout\Block\Checkout\ModifyCheckout $block 
*/

$storePhone = $block->getStorePhone();

?>

<div id="banner" data-bind="scope: 'banner'">
<!-- ko if: isVisible -->
<h3>Welcome <span data-bind="text: new String('<?= ('%1') ?>').replace('%1', customer().firstname)"></span><span>! Our web store id is </span><span><?php echo $storePhone; ?>.</span></h3>
<!-- /ko -->
</div>
<script type="text/x-magento-init">
{
"*": {
"Magento_Ui/js/core/app": {
"components": {
"banner": {
"component": "Macademy_CustomCheckout/js/view/banner"
}
}
}
}
}
</script>
