<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable

/** @var $block \Magento\Wishlist\Block\Customer\Wishlist\Button */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
    <button type="submit" name="save_and_share" title="<?= $escaper->escapeHtml(__('Share Wish List')) ?>" class="action share primary">
        <span><?= $escaper->escapeHtml(__('Share Wish List')) ?></span>
    </button>
<?php endif;?>
