<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable
/** @var \Magento\Framework\Escaper $escaper */

?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button type="button" data-role="all-tocart" title="<?= $escaper->escapeHtml(__('Add All to Cart')) ?>" class="action tocart primary">
        <span><?= $escaper->escapeHtml(__('Add All to Cart')) ?></span>
    </button>
<?php endif;?>
