<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable

?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write')) ?> <b><?= $block->escapeHtml(__('Us')) ?></b></span></legend><br />
        <div class="fieldset row">
            <div class="fields col-md-6">
              <div class="field name required">
                  <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                  <div class="control">
                      <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                  </div>
              </div>
              <div class="field email required">
                  <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                  <div class="control">
                      <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                  </div>
              </div>
              <div class="field telephone">
                  <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                  <div class="control">
                      <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="" class="input-text" type="text" />
                  </div>
              </div>
            </div>
            <div class="fields col-md-6">
              <div class="field comment required">
                  <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
                  <div class="control">
                      <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}"></textarea>
                  </div>
              </div>
              <?php echo $block->getChildHtml('form.additional.info'); ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
