<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable
/** @var \Magento\Framework\Escaper $escaper */

?>
<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');

    $title = $_helper->getConfig('porto_settings/footer/footer_newsletter_title');//"Be the First to Know";
    $sub_title = $_helper->getConfig('porto_settings/footer/footer_newsletter_text');//"Get all the latest information on Events,<br>Sales and Offers. Sign up for newsletter today.";
?>
<div class="block newsletter">
    <div class="block-title"><strong><?= $escaper->escapeHtml(__($title)); ?></strong></div>
    <div class="content">
        <p><?= $escaper->escapeHtml(__($sub_title)); ?></p>
        <label for="footer_newsletter"><?= $escaper->escapeHtml(__('Enter your email address')) ?></label>
        <form class="form subscribe"
            novalidate
            action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="footer_newsletter"><span><?= $escaper->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="footer_newsletter"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $escaper->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span><?= $escaper->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
