<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable

?>
<form class="form single-subscribe subscribe"
    novalidate
    action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail-1">
    <div class="field newsletter">
        <div class="control">
          <span class="input-text">
            <input name="email" placeholder="<?= $block->escapeHtmlAttr(__('Email Address')); ?>" type="email" id="newsletter" data-validate="{required:true, 'validate-email':true}"/>
          </span>
          <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
              <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
          </button>
        </div>
    </div>
</form>
